---
AWSTemplateFormatVersion: "2010-09-09"

Description: Depository app using S3, Lambda, and API Gateway

Resources:
  DepositoryS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: depositorybalance24

  DepositoryLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: IAM Role for Lambda to access S3
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      RoleName: DepositoryLambdaExecutionRole
